name: Publish NuGet
on:
  push:
    branches:
      - master

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: playstudios/action-nuget-publish-all@v1
        with:
          token: ${{ github.token }}
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
